version: '3'
networks:
  hss:
    ipam:
      config:
        - subnet: "17.31.0.0/16"
services:
  pyhss:
    build: .
    image: pyhss
    container_name: pyhss
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=hss-1
    volumes:
      - ./pyhss:/mnt/hss
    expose:
      - "3868/tcp"
      - "3868/sctp"
    ports:
      - "3868:3868/tcp"
      - "3868:3868/sctp"
    networks:
      hss:
        ipv4_address: "17.31.0.2"
